### ISSUE TITLE
en0: error fetching interface information: Device not found

### ISSUE THREAD

**Issue by siddharthcurious** [elviejokike/flask-eureka#3]
```
Traceback (most recent call last):
  File "app2.py", line 17, in <module>
    eureka.register_service(name="my-flask-service")
  File "/home/modak/Codebase/Modak/git_repos/enod-ws-v2.0/flask_eureka/eureka.py", line 57, in register_service
    **kwargs)
  File "/home/modak/Codebase/Modak/git_repos/enod-ws-v2.0/flask_eureka/eurekaclient.py", line 93, in __init__
    host_info = HostInfo().get()
  File "/home/modak/Codebase/Modak/git_repos/enod-ws-v2.0/flask_eureka/hostinfo.py", line 35, in get
    'IPv4': self.ipv4(),
  File "/home/modak/Codebase/Modak/git_repos/enod-ws-v2.0/flask_eureka/hostinfo.py", line 54, in ipv4
    ipv4 = ipv4.split(':')[1]
IndexError: list index out of range
==============================================================
Running on VMWare Ubuntu 16.04 
ubuntu $ ifconfig
docker0   Link encap:Ethernet  HWaddr 02:42:03:58:88:94  
          inet addr:172.17.0.1  Bcast:0.0.0.0  Mask:255.255.0.0
          inet6 addr: fe80::42:3ff:fe58:8894/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:270 errors:0 dropped:0 overruns:0 frame:0
          TX packets:516 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:213329 (213.3 KB)  TX bytes:80733 (80.7 KB)

ens33     Link encap:Ethernet  HWaddr 00:0c:29:35:45:d4  
          inet addr:192.168.206.135  Bcast:192.168.206.255  Mask:255.255.255.0
          inet6 addr: fe80::52f2:ed1:d777:2587/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:94076 errors:0 dropped:0 overruns:0 frame:0
          TX packets:53932 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:92354926 (92.3 MB)  TX bytes:6995641 (6.9 MB)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:39081 errors:0 dropped:0 overruns:0 frame:0
          TX packets:39081 errors:0 dropped:0 overruns:0 carrier:0

```

**Comment by Kirill-Bezugly** [comment]
I've got the same error. Actually I can't expect how it should work - interface always 'en0':

```
# grep -r en0 /usr/lib/python2.7/site-packages/flask_eureka
/usr/lib/python2.7/site-packages/flask_eureka/hostinfo.py:    def __init__(self, iface='en0'):
#
# grep -r 'HostInfo' /usr/lib/python2.7/site-packages/flask_eureka
/usr/lib/python2.7/site-packages/flask_eureka/eurekaclient.py:from .hostinfo import HostInfo
/usr/lib/python2.7/site-packages/flask_eureka/eurekaclient.py:        host_info = HostInfo().get()
/usr/lib/python2.7/site-packages/flask_eureka/hostinfo.py:class HostInfo(object):
#
```
